### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by saakeman** [tiliado/nuvola-app-grooveshark#1]
> Failed to initialize a core component main.js located at '/usr/share/nuvolaplayer3/js/main.js'. Initialization exited with error:
> 
> file:///usr/share/nuvolaplayer3/js/main.js:156: TypeError: undefined is not a function (evaluating 'this.addSignal("MediaKeyPressed")')
> 
> The application has reached an inconsistent state and will quit for that reason.

Running on Manjaro 0.8.12, 64 bit. Linux kernel 3.19.0-1.
Nuvola player 3 beta - 3.0.0

**Comment by jiri-janousek** [comment]
Hi. I'm afraid I cannot reproduce your issue on my system. Note that Nuvola Player 3 is not officially supported in Manjaro linux, so my ability to help you with the issue may be limited.

Could you post somewhere ([GitHub Gist](https://gist.github.com/) or [Ubuntu pastebin](http://paste.ubuntu.com/)) file `/usr/share/nuvolaplayer3/js/main.js` from your system? Also, how did you installed Nuvola Player 3 and which revision/commit? (There are actually many commits labelled 3.0.0 Beta).

Jiří Janoušek, Nuvola Player Developer • _My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/)._

**Comment by saakeman** [comment]
https://gist.github.com/saakeman/fd3dda203a6603474bd7#file-main-js

Hope this can shed some light on the problem. 

Thank you.

**Comment by jiri-janousek** [comment]
I think I have found the cause of this issue. Could try out Nuvola Player from latest git master?

---

Jiří Janoušek, Nuvola Player Developer • _My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/)._

**Comment by saakeman** [comment]
Thank you!! This has fixed the problem. 

Great app and awesome support, keep it up!
