### ISSUE TITLE
Unacceptable TLS certificate

### ISSUE THREAD

**Issue by Jab2870** [tiliado/nuvola-app-grooveshark#3]
This is the message I get when trying to use it

![image](https://cloud.githubusercontent.com/assets/1909202/10863933/97a8488c-7fd4-11e5-9c10-e5a4846cdfd5.png)

**Comment by jiri-janousek** [comment]
Hello. Unfortunately, [Grooveshark is out of business](https://plus.google.com/110794636546911932554/posts/hccHq8qE1WV) since May 2015. Take look at [other streaming services](https://tiliado.eu/nuvolaplayer/) to find an alternative.

**Comment by Jab2870** [comment]
http://grooveshark.im/

It looks like it's working to me

**Comment by jiri-janousek** [comment]
Nuvola Player supported the original Grooveshark (grooveshark.com) and support was discontinued when this service went out of business. The "new Grooveshark" (grooveshark.im) seems to be a [re-branded MP3Juice](https://torrentfreak.com/resurrected-grooveshark-is-actually-an-mp3juices-clone-150506/) actually. Although the new Grooveshark is not currently supported by Nuvola Player, it could be in the future and I've created a ticket for it tiliado/nuvolaplayer#175. However, the list of streaming services to be implemented is pretty long. Do you have active Nuvola Patrons membership? If yes, I'll increase priority of this request.
